### ISSUE TITLE
Bump Cocoapods version after upgrade to Swift 4

### ISSUE THREAD

**Issue by graulund** [rnine/AMCoreAudio#17]
Hi there!

Thanks for a great project. I am having some issues with the newest version of this project present in CocoaPods, and I see that the code I received from the pod repo does not reflect the current state of the project here on GitHub.

Is there any way you could bump the version present on Cocoapods so the new fixes can be distributed? Thanks! :)

**Comment by rnine** [comment]
@graulund I'll look into this shortly. Thanks for your reminder! 👍

**Comment by rnine** [comment]
@graulund Just pushed version 3.2 with added Swift 4 support :)
