### ISSUE TITLE
Unable to add it to my project via Cocoapods or Swift Package Manager

### ISSUE THREAD

**Issue by amardeepsingh20** [rnine/AMCoreAudio#23]
While the demo project works fine, I am unable to add AMCoreAudio as a framework in my fresh project via Cocoapods. The pod install command works fine but then it is not added to the project. Since there is not much documentation around adding it to the project, I would be really grateful if anyone can guide me a bit here. 

Thanks

**Comment by rnine** [comment]
@amardeepsingh20 Hmm, I see. I forgot to tag my release using semantic versioning for SPM so I just tagged `3.4.0` and that should fix SPM support. Not sure what the problem may be with Cocoapods, but I'll investigate.

Thanks for reporting!

**Comment by amardeepsingh20** [comment]
It’s working now with Swift Package Manager! 

Thank you so much 💪🏻
