### ISSUE TITLE
AudioStream retain cycle

### ISSUE THREAD

**Issue by fbarbat** [rnine/AMCoreAudio#27]
Every time I close the mac lid there is a leak of an AudioStream instance.

The retain cycle is on AudioStream.propertyListenerBlock because it is implicitly strong capturing self. So AudioStream deinit was never called and cleanup never made.

I tried using weak var to break that cycle but that generates other issues.

As now there are no retain cycles, that means AudioStream instances are removed from the pool appropriately. However, that has two drawbacks:

- First one is that every time we query for devices we have now to register and unregister listeners for each involved stream. Is adding and removing a listener expensive in CoreAudio? Not a CoreAudio expert here and I am curious about the answer of that question but it looks expensive.
- The major issue is that AudioObjectRemovePropertyListenerBlock does not work well with Swift. https://stackoverflow.com/questions/34700371/coreaudio-audioobjectremovepropertylistener-not-working-in-swift So now we are leaking listeners instead of AudioStreams which makes the memory leak worse because AudioStreams at least were cached.

My workaround was to fork AMCoreAudio and remove those listeners altogether since we were not using them in the first place. However, this breaks AMCoreAudio API which is not ideal.

Any thoughts about how to fix the leak without breaking the API? Thanks!

**Comment by rnine** [comment]
@fbarbat Interesting — I'll look into this one. Thanks for reporting!
