### ISSUE TITLE
Hi can SimplyCoreAudio create HAL input device and output device?

### ISSUE THREAD

**Issue by iAladdin** [rnine/AMCoreAudio#38]
Hi @rnine, really impressed with your work.

I have two questions about SimplyCoreAudio:
- Can SCA create virtual input and out devices on Mac? I know soundflower and loopback can do this feature, loopback is closed source code, and soundflower source code is out of date.
- Can I manipulate audio data with SCA and push the audio data to the virtual output device? just like a audio filter in a mac app.

Thank you!

**Comment by rnine** [comment]
> Hi @rnine, really impressed with your work.

Thank you!

> 
> I have two questions about SimplyCoreAudio:
> 
> * Can SCA create virtual input and out devices on Mac? I know soundflower and loopback can do this feature, loopback is closed source code, and soundflower source code is out of date.

It can only create aggregate devices. For everything else you will need a custom HAL driver like NullAudio.driver (see https://developer.apple.com/documentation/coreaudio/creating_an_audio_server_driver_plug-in)

> * Can I manipulate audio data with SCA and push the audio data to the virtual output device? just like a audio filter in a mac app.

This is also something you'll probably want to do on the HAL driver layer.

> 
> Thank you!

Hope this helps!

**Comment by iAladdin** [comment]
Thank you for your help！

I am just starting to work with audio related programming. Is there any library or tool that you recommend to help develop HAL drivers? Just like SAC

**Comment by rnine** [comment]
@iAladdin The only advice I can give is to get familiar with the `NullAudio.driver` source code and use HALLab (included here https://download.developer.apple.com/Developer_Tools/Additional_Tools_for_Xcode_12.5/Additional_Tools_for_Xcode_12.5.dmg) where you can inspect device properties and notifications (or you may use SCA, of course.)
