### ISSUE TITLE
<Unknown Device Name>

### ISSUE THREAD

**Issue by mattgreen** [rnine/AMCoreAudio#40]
This may be more of a CoreAudio thing, but I was wondering when/if you've ever seen a device appear with a name of <Unknown Device Name> in the wild. I looked up the source and saw it happens when the `.name` property returns nil, and the `cachedDeviceName` is also nil: https://github.com/rnine/SimplyCoreAudio/blob/4ea044ddbd02f9a8c896747dad9c703e6d250d8e/Sources/SimplyCoreAudio/Public/AudioDevice.swift#L60

Curious if you know what this is from. I'll keep digging and report back what I find. I've only seen it while running my app for days on end.

**Comment by rnine** [comment]
Hmm, I am not sure I have ever seen this happen. This could only happen for a device that does not support the `kAudioObjectPropertyName` property.

**Comment by mattgreen** [comment]
Yeah, I think it may have been from a device that had a BT connection failure. Closing since it is a bear to track down, will reopen if I figure out how to make it happen again.
