### ISSUE TITLE
AudioDevice+VirtualMasterOutput.swift + XCode 13 = fail

### ISSUE THREAD

**Issue by waydabber** [rnine/AMCoreAudio#42]
XCode 13 won't compile `AudioDevice+VirtualMasterOutput.swift` because of the error `'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift`

Renaming every ...`_VirutalMasterVolume` to ...`_VirtualMainVolume` and every ...`_VirtualMasterBalance` to ...`_VirtualMainBalance` in the  file fixes the issue.

Thank you!

**Comment by ryanfrancesconi** [comment]
Just noting that this is the commit that broke everything before XCode 13.

I'm on 12.5.1

Might want to reopen this one for backwards compatibility.

**Comment by rnine** [comment]
> Just noting that this is the commit that broke everything before XCode 13.
> 
> I'm on 12.5.1
> 
> Might want to reopen this one for backwards compatibility.

Confirmed on Xcode ~~12.5.1~~ 12.4 running macOS 10.15.7.
