### ISSUE TITLE
setVirtualMainVolume does not work with scope: .input

### ISSUE THREAD

**Issue by michaelphagen** [rnine/AMCoreAudio#65]
The `setVirtualMainVolume` function fails when trying to set the input volume of a device (Avid HDX Interface) using `scope: .input` on MacOS Big Sur 11.6.1.

The function works properly when using the `.output` scope.

I do not have other interfaces available to test, however, I can set the input volume using `.setVolume(1.0, channel: 0, scope: .input)`, so I am using that as a workaround.

**Comment by rnine** [comment]
@michaelphagen This function can only be used with the `.output` scope.
