### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by kkostov** [rnine/AMCoreAudio#70]
Would it be possible to create/tag a new release of the library so recent improvements can be made available via SPM?
At the moment, the latest version available using Version rules is `4.0.1` which doesn't build in Xcode 14.

Thank you! 🙏

**Comment by rnine** [comment]
Tagged `4.1.0` — hope this fixes the issue for you!

**Comment by kkostov** [comment]
It did! 🎊 Thank you so much!
