### ISSUE TITLE
Adding package causes SwiftUI previews to fail

### ISSUE THREAD

**Issue by kkostov** [rnine/AMCoreAudio#71]
Adding SimplyCoreAudio to a new SwiftUI project as a dependency causes SwiftUI Previews to fail with the following diagnostic message:

Xcode 14.0 (14A309), macOS 12.6 (21G115)

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060000eaa7450):'SimplyCoreAudio'>
```
<img width="431" alt="Screenshot 2022-09-24 at 05 18 02" src="https://user-images.githubusercontent.com/4718042/192077913-94bda1a7-2a0f-4111-8cee-54412c69e40a.png">

I believe the issue is caused by the Package.swift setting the library type to `static`. According to the [docs](https://developer.apple.com/documentation/packagedescription/product/library(name:type:targets:)), explicit setting of `.dynamic` or `.static` should only be used if the library is only capable of functioning that way.

**Comment by rnine** [comment]
Merged. Thanks!
